/* =========================================================================
   Atlas access + all procedural tile art.
   -------------------------------------------------------------------------
   * Sprites come from urbantileset/urbantileset32x32.png using the trimmed
     rects in src/atlas_data.js (generated by tools/gen_atlas.py).
   * Ground / platform / water tiles have no source art in the urban kit (it is
     a decoration-only building kit with no road texture), so they are painted
     procedurally here from per-zone palettes. That keeps every collidable
     pixel under our control.
   ========================================================================= */
(function () {
  var T = AA.TILE;

  AA.atlas = {
    img: null,
    ready: false,
    failed: false,
    byId: {},
    // Index the generated rects immediately, at script-evaluation time. The
    // engine builds collision rects for solid props during init(), which runs
    // long before the PNG has finished loading - if the index waited for the
    // image, those props would silently have no collision.
    index: function () {
      AA.ATLAS.forEach(function (e) { AA.atlas.byId[e.id] = e; });
    },
    load: function (src) {
      AA.atlas.index();
      var img = new Image();
      img.onload = function () { AA.atlas.ready = true; };
      img.onerror = function () { AA.atlas.failed = true; };
      img.src = src;
      AA.atlas.img = img;
    },
  };

  AA.atlas.index();

  // Draw a manifest sprite at native pixel size, scaled.
  // anchor: 'bottom' (default) places (x,y) at the sprite's feet/base centre.
  AA.drawSprite = function (ctx, id, x, y, scale, opt) {
    var e = AA.atlas.byId[id];
    if (!e || !AA.atlas.ready) return false;
    opt = opt || {};
    var s = scale == null ? 1 : scale;
    var w = e.w * s, h = e.h * s;
    var dx = x, dy = y;
    var anchor = opt.anchor || 'bottom';
    if (anchor === 'bottom') { dx = x - w / 2; dy = y - h; }
    else if (anchor === 'center') { dx = x - w / 2; dy = y - h / 2; }
    ctx.save();
    if (opt.alpha != null) ctx.globalAlpha *= opt.alpha;
    if (opt.flip) {
      ctx.translate(dx + w, dy);
      ctx.scale(-1, 1);
      ctx.drawImage(AA.atlas.img, e.x, e.y, e.w, e.h, 0, 0, w, h);
    } else {
      ctx.drawImage(AA.atlas.img, e.x, e.y, e.w, e.h, dx, dy, w, h);
    }
    ctx.restore();
    return true;
  };

  // ---------------------------------------------------------------------
  // Zone palettes. Each zone gives the ground a different colour story:
  // Diag grass, State St pavement, the Huron riverbank, a construction lot and
  // the stadium lot. All are derived from the tileset's own palette so the
  // procedural tiles sit next to the cropped sprites without clashing.
  // ---------------------------------------------------------------------
  AA.ZONES = {
    diag:    { topA: '#7fbf4a', topB: '#4e8c2c', soil: '#8a6a3f', soilD: '#6b4f2a', soilL: '#a3855a', rock: '#5b4126' },
    street:  { topA: '#b9b2a0', topB: '#8b8574', soil: '#7d6a4e', soilD: '#5d4d36', soilL: '#9a8663', rock: '#4a3d2b' },
    river:   { topA: '#9c8f6d', topB: '#6f6449', soil: '#6f5c40', soilD: '#513f2b', soilL: '#8a7350', rock: '#3f3221' },
    build:   { topA: '#d8a05a', topB: '#a9762f', soil: '#96693a', soilD: '#6f4c26', soilL: '#c08a4d', rock: '#54401f' },
    stadium: { topA: '#a9a496', topB: '#7c7768', soil: '#6e6a5d', soilD: '#4f4c42', soilL: '#8d8879', rock: '#3d3b33' },
  };

  // Deterministic per-tile noise so dithering never shimmers between frames.
  function noise(x, y, salt) {
    var n = (x * 374761393 + y * 668265263 + salt * 1442695040) | 0;
    n = (n ^ (n >> 13)) * 1274126177 | 0;
    return ((n ^ (n >> 16)) >>> 0) / 4294967296;
  }
  AA.tileNoise = noise;

  function shade(hex, amt) {
    var c = parseInt(hex.slice(1), 16);
    var r = AA.clamp(((c >> 16) & 255) + amt, 0, 255);
    var g = AA.clamp(((c >> 8) & 255) + amt, 0, 255);
    var b = AA.clamp((c & 255) + amt, 0, 255);
    return 'rgb(' + (r | 0) + ',' + (g | 0) + ',' + (b | 0) + ')';
  }
  AA.shade = shade;

  // --- ground -----------------------------------------------------------------
  // A solid tile: a two-tone body plus a lit/dark edge. `edge` flags which
  // neighbours are empty so seams read correctly.
  AA.drawGroundTile = function (ctx, tx, ty, zone, edge, time) {
    var p = AA.ZONES[zone] || AA.ZONES.diag;
    var x = tx * T, y = ty * T;
    var top = edge.top;
    var base = p.soil, dark = p.soilD, light = p.soilL;

    ctx.fillStyle = base;
    ctx.fillRect(x, y, T, T);

    // soil speckle
    for (var i = 0; i < 14; i++) {
      var nx = x + Math.floor(noise(tx, ty, i) * T);
      var ny = y + Math.floor(noise(tx, ty, i + 40) * T);
      ctx.fillStyle = noise(tx, ty, i + 90) > 0.5 ? dark : light;
      ctx.fillRect(nx, ny, 3, 2);
      ctx.fillRect(nx + 2, ny + 4, 2, 2);
    }

    // subsurface banding
    ctx.fillStyle = 'rgba(0,0,0,0.10)';
    for (var b = 0; b < 4; b++) {
      var by = y + 6 + b * 8;
      ctx.fillRect(x, by, T, 2);
    }

    if (top) {
      ctx.fillStyle = p.topB;
      ctx.fillRect(x, y, T, 10);
      ctx.fillStyle = p.topA;
      ctx.fillRect(x, y, T, 5);
      // grass blades / grit along the lip
      for (var g = 0; g < 7; g++) {
        var gx = x + Math.floor(noise(tx, ty, g + 7) * (T - 3));
        var gh = 3 + Math.floor(noise(tx, ty, g + 13) * 4);
        ctx.fillStyle = p.topA;
        ctx.fillRect(gx, y - gh, 2, gh);
        ctx.fillStyle = shade(p.topB, -18);
        ctx.fillRect(gx + 2, y - gh + 1, 1, gh - 1);
      }
      ctx.fillStyle = 'rgba(255,255,255,0.16)';
      ctx.fillRect(x, y, T, 2);
    }
    if (edge.left) { ctx.fillStyle = 'rgba(0,0,0,0.22)'; ctx.fillRect(x, y, 2, T); }
    if (edge.right) { ctx.fillStyle = 'rgba(0,0,0,0.22)'; ctx.fillRect(x + T - 2, y, 2, T); }
    if (edge.bottom) { ctx.fillStyle = 'rgba(0,0,0,0.30)'; ctx.fillRect(x, y + T - 3, T, 3); }
    // occasional embedded rock
    if (noise(tx, ty, 200) > 0.86) {
      ctx.fillStyle = p.rock;
      ctx.fillRect(x + 8, y + 14, 10, 7);
      ctx.fillStyle = shade(p.rock, 26);
      ctx.fillRect(x + 8, y + 14, 10, 2);
    }
    // brick courses in paved zones
    if (zone === 'street' || zone === 'stadium') {
      ctx.fillStyle = 'rgba(0,0,0,0.16)';
      ctx.fillRect(x, y + 16, T, 1);
      ctx.fillRect(x + ((ty % 2) ? 0 : 16), y + 16, 1, T - 16);
      ctx.fillRect(x, y + 25, T, 1);
    }
  };

  // Wooden plank platform (=): drawn as a 12px-thick deck.
  AA.drawPlankTile = function (ctx, tx, ty, time) {
    var x = tx * T, y = ty * T;
    var h = 14;
    ctx.fillStyle = '#7a4f26';
    ctx.fillRect(x, y, T, h);
    ctx.fillStyle = '#a06b33';
    ctx.fillRect(x, y, T, 4);
    ctx.fillStyle = '#c08a45';
    ctx.fillRect(x, y, T, 2);
    ctx.fillStyle = 'rgba(0,0,0,0.28)';
    ctx.fillRect(x, y + h - 3, T, 3);
    ctx.fillRect(x + 15, y, 2, h);
    if ((tx % 3) === 0) { // support post every 3rd tile
      ctx.fillStyle = '#5d3a1a';
      ctx.fillRect(x + 6, y + h, 8, T - h);
      ctx.fillStyle = 'rgba(0,0,0,0.25)';
      ctx.fillRect(x + 11, y + h, 3, T - h);
    }
  };

  // Brick block (B) - a buildable/breakable-looking masonry cube.
  AA.drawBrickTile = function (ctx, tx, ty) {
    var x = tx * T, y = ty * T;
    ctx.fillStyle = '#a3452f';
    ctx.fillRect(x, y, T, T);
    ctx.fillStyle = '#8d3826';
    ctx.fillRect(x, y + 15, T, 2);
    ctx.fillRect(x, y + 30, T, 2);
    var row, col;
    for (row = 0; row < 2; row++) {
      var oy = y + row * 16;
      for (col = 0; col < 2; col++) {
        var ox = x + ((row % 2) ? 0 : 16) + col * 16;
        ctx.fillStyle = '#b9543a';
        ctx.fillRect(ox + 1, oy + 1, 14, 13);
        ctx.fillStyle = 'rgba(255,255,255,0.14)';
        ctx.fillRect(ox + 1, oy + 1, 14, 2);
        ctx.fillStyle = 'rgba(0,0,0,0.22)';
        ctx.fillRect(ox + 1, oy + 12, 14, 2);
      }
    }
  };

  // Water (w): non-solid, deadly to touch. Two animated highlight bands.
  AA.drawWaterTile = function (ctx, tx, ty, time, edge) {
    var x = tx * T, y = ty * T;
    var g = ctx.createLinearGradient(0, y, 0, y + T);
    g.addColorStop(0, '#3f86b8');
    g.addColorStop(0.5, '#2a6a9a');
    g.addColorStop(1, '#1d4f78');
    ctx.fillStyle = g;
    ctx.fillRect(x, y, T, T);
    if (edge.top) {
      // surface: a moving sine crest plus foam flecks
      ctx.fillStyle = '#9fd8f0';
      var amp = 2.2;
      for (var i = 0; i < T; i++) {
        var yy = y + Math.sin((x + i) * 0.16 + time * 2.4) * amp + 2;
        ctx.fillRect(x + i, yy, 1, 3);
      }
      ctx.fillStyle = 'rgba(255,255,255,0.5)';
      for (var f = 0; f < 3; f++) {
        var fx = x + ((Math.floor(time * 22 + f * 11 + tx * 7) % T) + T) % T;
        ctx.fillRect(fx, y + 3, 3, 1);
      }
    }
    ctx.fillStyle = 'rgba(255,255,255,0.08)';
    var sx = Math.sin(time * 1.6 + tx * 0.9) * 5;
    ctx.fillRect(x + 4 + sx, y + 13, 18, 2);
    ctx.fillRect(x + 14 - sx, y + 23, 12, 2);
  };

  // ---------------------------------------------------------------------
  // Ambient skyline. Skylines are pre-rendered once per level build so the
  // backdrop is a couple of drawImage calls instead of hundreds of tiles.
  // ---------------------------------------------------------------------
  AA.buildSkyline = function (zone, rng) {
    var cv = document.createElement('canvas');
    cv.width = 1400; cv.height = 420;
    var ctx = cv.getContext('2d');
    var spec = {
      diag:    { near: '#6f8f8a', far: '#8fa9a4', win: '#c9e6d8', towers: 12, seed: 7 },
      street:  { near: '#5a6b86', far: '#7b8ca6', win: '#ffe6a8', towers: 16, seed: 21 },
      river:   { near: '#5d7a6a', far: '#89a292', win: '#d8f0dc', towers: 9, seed: 33 },
      build:   { near: '#7a6a5e', far: '#9b8b7c', win: '#ffd9a0', towers: 11, seed: 44 },
      stadium: { near: '#5e6474', far: '#848b9c', win: '#ffeec2', towers: 13, seed: 55 },
    }[zone] || {};

    function towerRow(color, winColor, count, baseY, maxH, minH, seed, alpha) {
      var r = AA.makeRng(seed);
      ctx.globalAlpha = alpha;
      var slot = cv.width / count;
      for (var i = 0; i < count; i++) {
        var w = slot * (0.55 + r() * 0.4);
        var h = minH + r() * (maxH - minH);
        var x = i * slot + (slot - w) * r();
        var y = baseY - h;
        ctx.fillStyle = color;
        ctx.fillRect(x, y, w, h);
        // roof furniture
        if (r() > 0.6) ctx.fillRect(x + w * 0.2, y - 12 * r() - 6, w * 0.28, 14);
        if (r() > 0.75) ctx.fillRect(x + w * 0.55, y - 22 * r() - 8, 5, 26);
        // windows
        ctx.fillStyle = winColor;
        for (var wy = y + 8; wy < baseY - 10; wy += 16) {
          for (var wx = x + 6; wx < x + w - 8; wx += 14) {
            if (r() > 0.42) ctx.fillRect(wx, wy, 6, 8);
          }
        }
      }
      ctx.globalAlpha = 1;
    }

    towerRow(spec.far, spec.win, spec.towers, 400, 250, 110, spec.seed, 0.55);
    towerRow(spec.near, spec.win, Math.max(4, spec.towers - 5), 410, 320, 150, spec.seed + 3, 0.9);

    // Ann Arbor is a tree town: canopy silhouette along the very top of the
    // backdrop so the skyline never reads as a bare generic city.
    var r2 = AA.makeRng(spec.seed + 99);
    for (var i = 0; i < 46; i++) {
      var cx = r2() * cv.width, cy = 40 + r2() * 120, cr = 14 + r2() * 30;
      ctx.fillStyle = 'rgba(56,104,60,' + (0.20 + r2() * 0.20).toFixed(2) + ')';
      ctx.beginPath();
      ctx.arc(cx, cy, cr, 0, Math.PI * 2);
      ctx.arc(cx + cr * 0.7, cy + 6, cr * 0.7, 0, Math.PI * 2);
      ctx.arc(cx - cr * 0.7, cy + 8, cr * 0.65, 0, Math.PI * 2);
      ctx.fill();
    }

    // ground haze so the backdrop meets the terrain softly
    var g = ctx.createLinearGradient(0, 250, 0, 420);
    g.addColorStop(0, 'rgba(255,255,255,0)');
    g.addColorStop(1, 'rgba(226,240,248,0.85)');
    ctx.fillStyle = g;
    ctx.fillRect(0, 250, cv.width, 170);
    return cv;
  };

  // Decorative campus hedge (H) - standalone, non-solid.
  AA.drawHedge = function (ctx, x, y, w, h, time) {
    var g = ctx.createLinearGradient(0, y, 0, y + h);
    g.addColorStop(0, '#5fa63c');
    g.addColorStop(1, '#2f6a24');
    ctx.fillStyle = g;
    ctx.fillRect(x, y + 4, w, h - 4);
    ctx.fillStyle = '#79c24e';
    for (var i = 0; i < w; i += 6) {
      var bh = 4 + Math.abs(Math.sin(i * 0.7 + x * 0.05)) * 5;
      ctx.fillRect(x + i, y + 4 - bh, 6, bh + 2);
    }
    ctx.fillStyle = 'rgba(0,0,0,0.22)';
    ctx.fillRect(x, y + h - 3, w, 3);
  };
})();
