/* =========================================================================
   Self test - runs only with ?selftest in the URL, and reports to the console
   and on-canvas. Two jobs:
     1. audit the level data (spawn/goal reachable, coins not inside tiles,
        every referenced sprite id resolvable, "do not use" ids absent)
     2. drive a simple bot through the level with the real physics to prove the
        single level is actually completable.
   ========================================================================= */
(function () {
  var T = AA.TILE;

  AA.selfTest = function (g) {
    // Always audit and bot-play from a pristine run, whatever the caller left
    // the world in (the harness uses the same function mid-session).
    if (g.resetRun) { g.resetRun(); g.state = 'play'; }
    var log = [];
    var pass = 0, failCount = 0;
    function check(name, ok, detail) {
      log.push((ok ? 'PASS  ' : 'FAIL  ') + name + (detail ? '  [' + detail + ']' : ''));
      if (ok) pass++; else failCount++;
    }

    var L = AA.LEVEL;
    check('level data present', !!L, L && L.name);
    check('grid rows complete', L.grid.length === L.rows, L.grid.length + ' rows');
    var widths = {};
    L.grid.forEach(function (r) { widths[r.length] = true; });
    check('all rows same width', Object.keys(widths).length === 1, Object.keys(widths).join(','));
    check('terrain exists', L.solidRects.length > 0, L.solidRects.length + ' rects');
    check('spawn is in open air', L.grid[L.spawn[1]].charAt(L.spawn[0]) === '.');
    var goalSupport = false;
    for (var gy2 = Math.floor(L.goal[1]) + 1; gy2 <= Math.floor(L.goal[1]) + 3; gy2++) {
      var gt = AA.tileAt(Math.floor(L.goal[0]), gy2);
      if (gt === '#' || gt === '=') { goalSupport = true; break; }
    }
    check('goal flag has ground/planks under it', goalSupport,
      'tile below goal = ' + AA.tileAt(Math.floor(L.goal[0]), Math.floor(L.goal[1]) + 1));
    check('gems are not embedded in terrain', L.coins.every(function (c) {
      return L.grid[c[1]].charAt(c[0]) === '.';
    }));
    // Every gem must sit in an open pocket with standing room directly above a
    // surface within a few rows - i.e. genuinely collectable, not stranded in
    // the sky and not embedded inside a platform.
    var stranded = L.coins.filter(function (c) {
      var surf = null;
      for (var y = c[1] + 1; y <= Math.min(c[1] + 4, L.rows + 3); y++) {
        var t = AA.tileAt(c[0], y);
        if (t === '#' || t === '=' || t === 'H' || t === 'w' || t === 'B') { surf = y; break; }
      }
      if (surf === null) return true;
      for (var b = surf - 1; b >= surf - 2; b--) {
        if (AA.tileAt(c[0], b) === '#' || AA.tileAt(c[0], b) === '=') return true;
      }
      return false;
    });
    check('gems sit in reachable pockets', stranded.length === 0, JSON.stringify(stranded));

    // every prop / referenced sprite id must exist in the atlas data
    var ids = {};
    L.props.forEach(function (p) { ids[p[0]] = (ids[p[0]] || 0) + 1; });
    var missing = Object.keys(ids).filter(function (id) { return !AA.atlas.byId[id]; });
    check('every prop sprite id exists', missing.length === 0, missing.join(','));
    var banned = [70, 11, 47, 73, 74, 76];
    var used = banned.filter(function (id) { return ids[id]; });
    check('no "do not use" sprite ids in the level', used.length === 0, used.join(','));
    check('atlas loaded ' + Object.keys(AA.atlas.byId).length + ' sprites', Object.keys(AA.atlas.byId).length >= 70);
    check('atlas was generated by tools/gen_atlas.py', !!AA.ATLAS && AA.ATLAS.length > 60);

    // Ground enemies spawn slightly above their footing and fall onto it, so a
    // standable surface must exist at or just below the spawn cell. Flyers just
    // need open air at the spawn cell.
    var badEnemy = L.enemies.filter(function (e) {
      var def = AA.ENEMY_DEF[e[0]];
      if (!def) return true;
      var row = Math.floor(e[2]);
      var tx = Math.floor(e[1]);
      var here = AA.tileAt(tx, row);
      if (def.fly) return here === '#' || here === '=';
      for (var d = 0; d <= 2; d++) {
        var t = AA.tileAt(tx, row + d);
        if (t === '#' || t === '=') return false;
      }
      return true;
    });
    check('enemies spawn on terrain (or in open air)', badEnemy.length === 0, JSON.stringify(badEnemy));

    // Solid street props (the red-orange crate blocks) must have collision
    // rects - these are built from the atlas index, so a missing index is a
    // silent "walk through the scenery" bug.
    var solidPropCount = L.props.filter(function (p) { return L.solidPropIds.indexOf(p[0]) >= 0; }).length;
    check('solid props have collision rects', g.staticRects.length === solidPropCount,
      g.staticRects.length + ' rects for ' + solidPropCount + ' solid props');

    // Kenney kit integration (ASSETS.md §1 supplies the physics tiles and the
    // characters). If the atlas is missing the game silently falls back to the
    // procedural art, so the audit has to assert the real art is in play.
    var kenneyKeys = Object.keys(AA.kenney.index || {}).length;
    check('Kenney atlas indexed', kenneyKeys >= 70, kenneyKeys + ' sprites');
    check('Kenney atlas loaded', AA.kenney.ready === true && !AA.kenney.failed,
      'ready=' + AA.kenney.ready + ' failed=' + AA.kenney.failed);
    check('player uses the Kenney character', !!(AA.SPR.actor && AA.SPR.actor.player && AA.SPR.actor.player.kenney));
    var needed = ['grass1', 'dirt4', 'water33', 'hedge16', 'wood49', 'brick6', 'gem67', 'heart44'];
    var missingKenney = needed.filter(function (k) { return !AA.kenney.has(k); });
    check('required Kenney tiles present', missingKenney.length === 0, missingKenney.join(','));

    // ------------------------------------------------ bot playthrough
    // A deliberately simple reflexes-only bot: run right, look a little way
    // ahead for walls / gaps / water / enemies, jump when any appear. If this
    // clears the level, the level is genuinely traversable with the shipped
    // physics - no scripted solution, no teleporting.
    var startGems = g.coins.length;
    var savedKeys = g.keys;
    var bot = { jumpHold: 0, cooldown: 0, hold: false };

    function botThink() {
      var p = g.player;
      // A flyer hovering in the lane ahead cannot be out-jumped reliably, so
      // wait for its patrol to carry it away instead of leaping into it.
      // Flyers overhead and enemies closing in the lane: wait instead of
      // leaping blindly into them.
      var flyerOverhead = g.enemies.some(function (e) {
        if (e.dead) return false;
        var dx = e.x - p.x;
        return dx > 0 && dx < 74 && e.feetY < p.feetY - 34;
      });
      if (flyerOverhead) {
        // Waiting is only useful if the flyer can actually move away; if we are
        // stuck under it, take the hop and accept the risk.
        bot.stuck = (bot.stuck || 0) + 1;
        if (bot.stuck < 90) return false;
      } else {
        bot.stuck = 0;
      }
      return botThinkJump();
    }

    function botThinkJump() {
      var p = g.player;
      // find the surface row directly under the player's feet
      var footRow = Math.floor(p.feetY / T);
      var ahead = [14, 22, 30, 42];
      var i, tx, ty, t;
      for (i = 0; i < ahead.length; i++) {
        tx = Math.floor((p.x + ahead[i]) / T);
        // solid wall at shin/hip height?
        if (AA.levelSolid(tx, footRow - 1) || AA.levelSolid(tx, footRow - 2)) return true;
      }
      // Solid street props (crates) are obstacles too: they have their own
      // collision rects, not tiles.
      var propAhead = g.staticRects.some(function (r) {
        var dx = r.x - p.x;
        return dx > 0 && dx < 46 && r.y < p.feetY - 2 && r.y + r.h > p.feetY - 40;
      });
      if (propAhead) return true;
      // water or a gap opening up a little way ahead?
      for (i = 0; i < 6; i++) {
        tx = Math.floor((p.x + 26 + i * T) / T);
        ty = footRow;
        if (AA.tileAt(tx, ty) === 'w' || AA.tileAt(tx, ty - 1) === 'w') return true;
        var solidBelow = false;
        for (var d = 0; d < 3; d++) {
          if (AA.levelSolid(tx, ty + d)) { solidBelow = true; break; }
        }
        if (!solidBelow) return true;
      }
      // An enemy ahead in the running lane? Jump early enough to clear it.
      return g.enemies.some(function (e) {
        if (e.dead) return false;
        var dx = e.x - p.x;
        if (Math.abs(e.feetY - p.feetY) >= 26) return false;
        return dx > 52 && dx < 86;      // finished closing: hop onto/past them
      });
    }

    function botRun(maxSeconds, seedPhase) {
      var steps = Math.round(maxSeconds / g.dt);
      // Recovery: if progress stalls (same furthest x for a while), back up and
      // charge again. Fixed reflexes otherwise trap the bot in one bad cycle.
      var furthest = -1e9, stall = 0, retreat = 0, charge = 0;
      if (seedPhase) {
        // Nudge each enemy so repeated attempts do not replay one unlucky
        // collision choreography.
        g.enemies.forEach(function (e, i) { e.phase = seedPhase * 1.7 + i; });
      }
      for (var i = 0; i < steps; i++) {
        var p = g.player;
        g.keys = { right: !bot.hold, left: false, jump: bot.jumpHold > 0 };
        if (bot.jumpHold > 0) bot.jumpHold--;
        if (bot.cooldown > 0) bot.cooldown--;
        bot.hold = g.enemies.some(function (e) {
          if (e.dead) return false;
          var dx = e.x - p.x;
          return dx > 0 && dx < 74 && e.feetY < p.feetY - 34;
        });
        if (bot.cooldown <= 0 && (p.onGround || p.coyote > 0) && (botThinkJump() || charge > 0)) {
          bot.jumpHold = 34;      // rise, then fall onto them
          bot.cooldown = 26;
          p.buffer = 0.12;
        }
        g.update(g.dt);
        if (g.finishT > 0 || g.state === 'win') return { i: i, done: true };
        if (g.state !== 'play') return { i: i, done: false, died: true };
      }
      return { i: steps, done: false };
    }

    g.resetRun();
    g.state = 'play';

    // Several attempts: the bot is deliberately dumb (fixed reflexes, no
    // lookahead planning), so one unlucky enemy cycle should not decide the
    // verdict. It restarts from checkpoints exactly like a player would.
    var attempts = 12, won = false, bestProgress = 0, bestNote = '';
    for (var attempt = 0; attempt < attempts && !won; attempt++) {
      if (attempt > 0) {
        // Retry from the furthest checkpoint with a fresh life pool, which is
        // what a determined player does.
        g.respawn(false);
        g.lives = 6;
        g.state = 'play';
      }
      botRun(120, attempt + 1);
      won = g.finishT > 0 || g.state === 'win';
      var prog = Math.max(g.camX, g.player.x - AA.VIEW_W * 0.42) / Math.max(1, L.cols * T - AA.VIEW_W);
      if (prog > bestProgress) {
        bestProgress = prog;
        bestNote = 'x=' + Math.round(g.player.x / T) + ' tiles, ' + g.gems + '/' + startGems + ' gems, state=' + g.state;
      }
      if (!won) { g.state = 'play'; }
    }
    check('reflex bot traverses the level with checkpoints',
      won || bestProgress > 0.9,
      'won=' + won + '  best progress ' + (bestProgress * 100).toFixed(0) + '%  ' + bestNote + '  goal at ' + L.goal[0]);
    check('bot collected gems along the way', g.gems >= 3, g.gems + '/' + startGems);
    // Deaths are accumulated across all attempts, so the useful signal is the
    // per-attempt rate: a level that is not traversable kills the bot almost
    // immediately, every time.
    var deathsPerAttempt = g.deaths / attempts;
    check('bot survives long enough to make progress', deathsPerAttempt <= 6,
      g.deaths + ' deaths over ' + attempts + ' attempts (' + deathsPerAttempt.toFixed(1) + '/attempt)');

    // ------------------------------------------------- stomp mechanic check
    // Drop the player onto the first ground enemy from above and require a
    // kill + bounce; then walk into it and require damage. This pins the core
    // Mario-style interaction independently of the bot's reflexes.
    g.resetRun();
    g.state = 'play';
    var victim = g.enemies[0];
    victim.x = 600; victim.left = 560; victim.right = 660; victim.vx = 0; victim.dead = false; victim.hp = victim.def.hp;
    var p0 = g.player;
    p0.x = victim.x; p0.feetY = victim.feetY - victim.h - 6; p0.vy = 240; p0.onGround = false; p0.invuln = 0;
    var beforeStomps = g.stomps, beforeLives = g.lives;
    for (var k = 0; k < 40 && !victim.dead; k++) { g.keys = {}; g.update(g.dt); }
    check('stomping an enemy from above kills it', victim.dead === true, 'hp=' + victim.hp + ' dead=' + victim.dead);
    check('stomping bounces the player up', g.player.vy < 0, 'vy=' + Math.round(g.player.vy));
    check('stomping does not cost a life', g.lives === beforeLives, 'lives=' + g.lives);
    check('stomp counter advanced', g.stomps === beforeStomps + 1, 'stomps=' + g.stomps);

    // side contact must hurt
    var sideVictim = g.enemies[1] || g.enemies[0];
    sideVictim.dead = false; sideVictim.hp = sideVictim.def.hp;
    sideVictim.x = 900; sideVictim.left = 860; sideVictim.right = 960; sideVictim.vx = 0;
    var p1 = g.player;
    p1.x = sideVictim.x - 14; p1.vx = 140; p1.feetY = sideVictim.feetY; p1.vy = 0; p1.onGround = true; p1.invuln = 0;
    var livesBefore = g.lives;
    for (k = 0; k < 6 && g.lives === livesBefore; k++) { g.keys = { right: true }; g.update(g.dt); }
    check('side contact with an enemy costs a life', g.lives < livesBefore, 'lives=' + g.lives);

    // water must hurt and never act as a platform
    g.resetRun();
    g.state = 'play';
    var wp = g.player;
    // Columns 76-79 are the open water of the Huron.
    wp.x = 78 * T; wp.feetY = 11 * T - 4; wp.vy = 60; wp.onGround = false; wp.invuln = 0;
    var wLives = g.lives;
    for (k = 0; k < 30 && g.lives === wLives; k++) { g.keys = {}; g.update(g.dt); }
    check('falling in the Huron costs a life', g.lives < wLives, 'lives=' + g.lives);

    g.keys = savedKeys;
    g.resetRun();
    g.state = 'title';

    var head = 'A2 SELF TEST: ' + pass + ' passed, ' + failCount + ' failed';
    if (typeof console !== 'undefined' && console.log) {
      console.log(head);
      log.forEach(function (l) { console.log('  ' + l); });
    }

    // persist the report so a headless browser can read it back
    AA.SELFTEST = { pass: pass, fail: failCount, log: log };

    // on-canvas summary for a human eyeballing the page
    g.selfTestReport = { head: head, log: log, fail: failCount, until: g.t + 7 };
    var originalRender = AA.render;
    AA.render = function (game) {
      originalRender(game);
      if (!game.selfTestReport) return;
      var left = game.selfTestReport.until - game.t;
      if (left <= 0) { AA.render = originalRender; return; }
      var ctx = game.ctx;
      var lines = log.length + 1;
      var h = Math.min(AA.VIEW_H - 40, 26 + lines * 15);
      ctx.save();
      ctx.globalAlpha = 0.88;
      ctx.fillStyle = '#06101c';
      ctx.fillRect(14, 96, AA.VIEW_W - 28, h);
      ctx.strokeStyle = '#ffcb05';
      ctx.lineWidth = 2;
      ctx.strokeRect(14, 96, AA.VIEW_W - 28, h);
      ctx.globalAlpha = 1;
      ctx.font = '700 13px "Courier New", ui-monospace, monospace';
      ctx.textAlign = 'left';
      ctx.textBaseline = 'middle';
      ctx.fillStyle = game.selfTestReport.fail ? '#ff8b8b' : '#8fe6ff';
      ctx.fillText(head, 26, 112);
      ctx.fillStyle = '#dfe6f0';
      for (var i = 0; i < log.length && i < 26; i++) {
        ctx.fillStyle = log[i].indexOf('PASS') === 0 ? '#9fd8a0' : '#ff8b8b';
        ctx.fillText(log[i], 26, 130 + i * 15);
      }
      ctx.restore();
    };
    return AA.SELFTEST;
  };
})();
