#!/usr/bin/env python3
"""Generate src/atlas_data.js from the real pixels of the urban tileset.

Reads manifest/urban_tileset_manifest.json for the per-sprite rects, then
re-derives each rect's *trimmed* opaque bounding box straight from the PNG so
the runtime never has to draw transparent padding.  Sprites flagged
"do not use" in ASSETS.md are dropped here, which is the single place that
policy is enforced.

Run:  python3 tools/gen_atlas.py
"""
from PIL import Image
import json, collections, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, 'urbantileset', 'urbantileset32x32.png')
MAN = os.path.join(ROOT, 'manifest', 'urban_tileset_manifest.json')

# ASSETS.md "Flagged - do not use as plain decoration":
#   70 = rooftop billboard with the artist's name baked in (credits screen only)
#   11,47,73,74,76 = flat solid-colour palette swatches
SKIP = {11, 47, 70, 73, 74, 76}
# Merged auto-detected blobs - usable as one background chunk, never sliced.
CLUSTERS = {54, 71}


def main():
    im = Image.open(SRC).convert('RGBA')
    px = im.load()
    W, H = im.size
    man = json.load(open(MAN))

    def palette(x, y, w, h, maxc=6):
        c = collections.Counter()
        for j in range(y, y + h):
            for i in range(x, x + w):
                r, g, b, a = px[i, j]
                if a > 16:
                    c[(r, g, b)] += 1
        tot = sum(c.values()) or 1
        return [{'c': '#%02x%02x%02x' % k, 'a': round(n / tot, 3)}
                for k, n in c.most_common(maxc)]

    entries = []
    for s in man['sprites']:
        if s['id'] in SKIP:
            continue
        x, y, w, h = s['x'], s['y'], s['w'], s['h']
        minx, miny, maxx, maxy = 10 ** 9, 10 ** 9, -1, -1
        for j in range(y, min(y + h, H)):
            for i in range(x, min(x + w, W)):
                if px[i, j][3] > 16:
                    minx = min(minx, i); miny = min(miny, j)
                    maxx = max(maxx, i); maxy = max(maxy, j)
        if maxx < 0:
            print('  ! sprite %d had no opaque pixels, skipped' % s['id'])
            continue
        tw, th = maxx - minx + 1, maxy - miny + 1
        entries.append({
            'id': s['id'], 'x': minx, 'y': miny, 'w': tw, 'h': th,
            'label': s['label'], 'cat': s['category'],
            'cluster': s['id'] in CLUSTERS,
            'pal': palette(minx, miny, tw, th),
        })

    out = os.path.join(ROOT, 'src', 'atlas_data.js')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w') as f:
        f.write('/* GENERATED by tools/gen_atlas.py from urbantileset/urbantileset32x32.png\n')
        f.write("   Rects are trimmed to each sprite's real opaque bounding box.\n")
        f.write('   Art (c) Dlou Saiyan - used under permission, credit required. */\n')
        f.write('window.AA = window.AA || {}; AA.ATLAS = ')
        json.dump(entries, f, separators=(',', ':'))
        f.write(';\n')

    print('kept %d sprites (skipped ids %s)' % (len(entries), sorted(SKIP)))
    for e in entries:
        print('  id=%3d %4dx%-4d %s' % (e['id'], e['w'], e['h'], e['label'][:56]))
    print('wrote %s (%d bytes)' % (out, os.path.getsize(out)))


if __name__ == '__main__':
    main()
